[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'

[[plugins]]
repo = 'mattn/gist-vim'
on_cmd = 'Gist'

[[plugins]]
repo  = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo  = 'tpope/vim-endwise'
on_ft = ['ruby']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'scss']
