[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]]
repo = 'AndrewRadev/switch.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'airblade/vim-rooter'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'noahfrederick/vim-skeleton'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
