#!/bin/sh

printf 'checking the path of dotfiles... '

basedir=`dirname $0`
DOTFILES_ROOT=`cd $basedir/../../ && pwd -P`
echo "DOTFILES_ROOT=$DOTFILES_ROOT" >> ~/.dotfiles.conf

printf '%s\n' $DOTFILES_ROOT
