#!/bin/sh

printf 'checking whether vim exists... '

if type vim > /dev/null 2>&1; then
	echo 'DOTFILES_VIM_EXISTS=1' >> ~/.dotfiles.conf
	printf 'yes\n'
else
	echo 'DOTFILES_VIM_EXISTS=0' >> ~/.dotfiles.conf
	printf 'no\n'
fi
