#!/bin/sh

printf 'checking what type of `ls` this environment has... '

DOTFILES_LSTYPE=unknown
if ls --color -d . >/dev/null 2>&1; then
    DOTFILES_LSTYPE=GNU
elif ls -G -d . >/dev/null 2>&1; then
    DOTFILES_LSTYPE=BSD
fi
echo "DOTFILES_LSTYPE=$DOTFILES_LSTYPE" >> ~/.dotfiles.conf

printf '%s\n' $DOTFILES_LSTYPE
