#!/bin/sh

if [ $# -lt 1 ]; then
	echo "Usage: $0 filename" >&2
	exit 1
fi

if ! read -r first; then
	echo "ERROR: the input is empty." >&2
	exit 1
fi

last="$first"
template="$first\n"
while read -r line; do
	last=$line
	template="$template$line\n"
done

variable_expansion() {
	perl -e 'while(<>){s/%([a-zA-Z0-9_]+)%/$ENV{$1}/eg;print}'
}
template=`printf "%s" "$template" | variable_expansion`

escape_regexp() {
	sed -E 's/(\/|\\|\.|\?|\*|\+|\^|\$|\[|\])/\\\1/g'
}
first=`echo "$first" | escape_regexp`
last=`echo "$last" | escape_regexp`

template_substitution() {
	touch $1
	awk -v template="$template" -f - $1<<EOT
BEGIN {
	state = 0
}

/^$first$/ {
	state = 1
	next
}

/^$last$/ { 
	state = 2
	printf "%s", template
	next
}

state == 1 {
	next
}

{ print }

END {
	if (state == 0) {
		printf "\\n%s\\n", template
	} else if (state == 1) {
		exit 1
	}
}
EOT
}
if replaced_config=`template_substitution $1`; then
	printf "%s\n" "$replaced_config" > $1
else
	echo "ERROR: Previously inserted configuration is broken." >&2
fi
