#!/bin/sh
set -e

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ROOT_DIR=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)

cd "$ROOT_DIR"

OS_ID=""

if [ -r /etc/os-release ]; then
    . /etc/os-release
    OS_ID="${ID:-}"
fi

# ----

if [ "$OS_ID" = "ubuntu" ]; then
    sudo apt update
    sudo apt install -y software-properties-common
    sudo add-apt-repository --yes --update ppa:ansible/ansible
    sudo apt install -y ansible

# ----

else
    echo "Unsupported platform. Please install Ansible manually."
    exit 1
fi

ansible-playbook site.yml --ask-become-pass
