---
- name: Remove old ~/.config/nvim/init.vim if present
  file:
    path: ~/.config/nvim/init.vim
    state: absent

- name: Insert configuration block in ~/.config/nvim/init.lua
  blockinfile:
    path: ~/.config/nvim/init.lua
    create: yes
    marker: "-- {mark} ANSIBLE MANAGED BLOCK"
    block: |
      vim.g.dotfiles_runtimepath = '{{ role_path }}/local_files'
      vim.opt.runtimepath:append(vim.g.dotfiles_runtimepath)

      local local_init = vim.fn.expand('~/.config/nvim/init.local.lua')
      if vim.fn.filereadable(local_init) == 1 then
        dofile(local_init)
      end
